### ISSUE TITLE
Streams not ended properly

### ISSUE THREAD

**Issue by comartmit** [dylang/node-xml#21]
Streams are only supposed to emit the 'end' event after all 'data' events are emitted. Unfortunately, the data is all being emitted after the 'end' event is emitted which renders a stream approach completely useless. You have no way of knowing the outputted xml object is done being generated short of forcing a timeout. The main culprit can be found in ```end()``` starting on line 50 of xml.js. I considered fixing it, but the entire stream implementation seems to be hacked together and I don't feel like reworking all of the logic to make a proper stream implementation. Going to cut over and just pass it the full object and avoid the streams.

**Comment by dylang** [comment]
I have to admit I accepted the streams PR without fully understanding it. If you have code that shows the problem I can use that for an error test in case somebody else is interested in attempting to fix the problem.

**Comment by harish2704** [comment]
Hi,

The problem can be reproduced with the following lines of code
```javascript

var xml = require('xml');
var l = console.log.bind( console );
var elem = xml.element({ _attr: { decade: '80s', locale: 'US'} });
var stream = xml({ toys: elem }, { stream: true });
stream.on('data',  l.bind(null,'Data: ') );
stream.on('end',  l.bind(null, 'stream end: ') );
stream.on('close',  l.bind(null, 'stream close: ') );
elem.push({ toy: 'Transformers' });
elem.push({ toy: 'GI Joe' });
elem.push({ toy: [{name:'He-man'}] });
elem.close();

/* Output
stream end: 
stream close: 
Data:  <toys decade="80s" locale="US">
Data:  <toy>Transformers</toy>
Data:  <toy>GI Joe</toy>
Data:  <toy><name>He-man</name></toy>
Data:  </toys>
*/
```

Actual output should be 
```
Data:  <toys decade="80s" locale="US">
Data:  <toy>Transformers</toy>
Data:  <toy>GI Joe</toy>
Data:  <toy><name>He-man</name></toy>
Data:  </toys>
stream end: 
stream close: 
```
