### ISSUE TITLE
Self closing empty tags

### ISSUE THREAD

**Issue by izatop** [dylang/node-xml#24]
Why does it not close empty tag?

**Comment by dylang** [comment]
It should. If you have an example that doesn't pass submit a PR with a test that fails and I'm happy to try to fix the issue. 

```js
t.is(xml([{a: {}}]), '<a/>');
t.is(xml([{a: null}]), '<a/>');
t.is(xml([{a: []}]), '<a></a>')
```

**Comment by izatop** [comment]
You can close the issue, i don't remember where i got it.

**Comment by dylang** [comment]
Thanks!

**Comment by kibertoad** [comment]
@dylang I believe this can be reproduced by having a node that has `_attr` child but no real children.

**Comment by donovanrichardson** [comment]
@kibertoad I was having the same issue, but after looking at this dylang's post here, I found that you can make an element self-closing by including the `_attr` as a direct child of the element instead of within an array.

```js
const theXml = {xml:[{_attr:{prop1:"val1",prop2:"val2",prop3:"val3"}}]} 
// ^^ returns <xml prop1="val1" prop2="val2" prop3="val3"></xml>

const theXml2 = {xml:{_attr:{prop1:"val1",prop2:"val2",prop3:"val3"}}} 
// ^^ returns <xml prop1="val1" prop2="val2" prop3="val3"/>

```
