### ISSUE TITLE
console log prettified xml?

### ISSUE THREAD

**Issue by tnrich** [dylang/node-xml#32]
Hey there, just wondering if you could add an option to prettify the xml that is spit out of this tool?

Thanks so much!

**Comment by Kriegslustig** [comment]
Hi! Noticed your question in passing. This functionality is already in this package. There are two options:

**Pass `true` as the second parameter**:

```
xml({ a: [ { b: 'something' } ]}, true) === '<a>\n    <b>something</b>\n</a>'
```

**Set the `indent` option to a string**:

```
xml({ a: [ { b: 'something' } ]}, { indent: '\t' }) === '<a>\n\t<b>something</b>\n</a>'
xml({ a: [ { b: 'something' } ]}, { indent: '  ' }) === '<a>\n  <b>something</b>\n</a>'
```

**Comment by ErisDS** [comment]
Hope this answered your question, let me know if not :)
